// Real-Time 60 FPS Wav2Lip Video Synthesis Renderer with Temporal Kalman Vertex Smoothing
// - Eliminates all micro-saccades and ghost traces ("aucune saccade ni trace fantôme") during head movements:
//   1. The foreground cutout (`aisha_cutout_foreground.png`) is a rembg/u2net ML matte with a feathered
//      ~1.2px alpha ramp and person-color bleed into the transparent zone (regenerated by
//      tools/make_aisha_cutout_rembg.py), so bilinear texture filtering never samples the old
//      photo background at the silhouette — no blue-gray slabs, no stair-stepped edges.
//   2. Per-vertex Temporal State-Space Smoothing (SMOOTH_DX/DY + VEL_DX/DY) ensures C²-continuous vertex trajectories.
// - Exact Reference Mouth Articulation Display Model (Open Vowel Panel A + Rounded Pucker Panel B) locked to the voice.

import imgTutrice from '../assets/images/aisha_cutout_foreground.png';
import imgStudioBg from '../assets/images/studio_static_background.jpg';
import type { AvatarComputedFrame } from '../workers/avatarExpressionWorker';

const IMG_W = 896;
const IMG_H = 1200;

// 19 Anatomical Columns:
// - c=0 (0), c=1 (202), c=17 (698), c=18 (896) are 100% static studio background anchors.
// - c=2 (278) .. c=16 (602) bound Aïsha's complete head, braided bun & earrings silhouette.
// - c=5..14 (408.0..500.0) are the 10 pixel-calibrated mouth stations.
const GRID_X: readonly number[] = [
  0, 202, 278, 355, 392,
  408.0, 418.0, 428.0, 438.0, 448.0, 458.0, 468.0, 478.0, 488.0, 500.0,
  520, 602, 698, 896,
];
const NUM_COLS = GRID_X.length; // 19

// 3D Perspective Yaw Weight across head columns c=2..16:
const YAW_PERSPECTIVE_W: readonly number[] = [
  0.00, // c=0 (static)
  0.00, // c=1 (static)
  0.82, // c=2 (left hair bun silhouette)
  0.90, // c=3 (left temple / outer brow)
  0.96, // c=4 (left eye / cheek)
  1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, 1.00, // c=5..14 (nose & mouth)
  0.96, // c=15 (right eye / cheek)
  0.82, // c=16 (right hair & ear silhouette)
  0.00, // c=17 (static)
  0.00, // c=18 (static)
];

// 10-station exact pixel-calibrated mouth contours (408.0, 484.0) -> (500.0, 484.0)
const UPPER_LIP_TOP_10 = [478.0, 474.5, 473.0, 472.0, 472.5, 472.5, 473.0, 474.0, 475.0, 479.0];
const UPPER_LIP_BOT_10 = [483.5, 482.5, 482.0, 481.5, 481.5, 481.5, 481.5, 482.0, 482.5, 483.5];
const UPPER_TEETH_BOT_10 = [484.0, 484.0, 484.0, 484.0, 484.0, 484.0, 484.0, 484.0, 484.0, 484.0];
const LOWER_LIP_TOP_10 = [484.5, 485.0, 485.2, 485.5, 485.5, 485.5, 485.5, 485.2, 485.0, 484.5];
const LOWER_LIP_BOT_10 = [491.0, 496.5, 501.0, 504.5, 506.5, 506.5, 505.0, 502.0, 497.5, 491.5];
const CHIN_JAW_10 = [550.0, 555.0, 559.0, 562.5, 564.5, 564.5, 562.5, 559.0, 555.0, 550.0];

// Symmetrical bilateral parabola of lower lip displacement across all 10 mouth stations
const STATION_DOME_W: readonly number[] = [
  0.20, // mIdx=0 (x=408.0): left commissure
  0.74, // mIdx=1 (x=418.0): left lateral mouth
  0.92, // mIdx=2 (x=428.0): left-mid mouth
  0.99, // mIdx=3 (x=438.0)
  1.00, // mIdx=4 (x=448.0)
  1.00, // mIdx=5 (x=458.0)
  0.99, // mIdx=6 (x=468.0)
  0.92, // mIdx=7 (x=478.0)
  0.74, // mIdx=8 (x=488.0)
  0.20, // mIdx=9 (x=500.0): right commissure
];

// Cervical neck pivot for expressive feminine head rotation, listening nods & inclination
const HEAD_PIVOT_X = 454.0;
const HEAD_PIVOT_Y = 538.0;

const NUM_ROWS = 19;
const TOTAL_VERTS = NUM_ROWS * NUM_COLS;

const REST_SX = new Float32Array(TOTAL_VERTS);
const REST_SY = new Float32Array(TOTAL_VERTS);

// Target & Temporally-Smoothed (Kalman state-space) vertex buffers
const TARGET_DX = new Float32Array(TOTAL_VERTS);
const TARGET_DY = new Float32Array(TOTAL_VERTS);
const CUR_DX = new Float32Array(TOTAL_VERTS);
const CUR_DY = new Float32Array(TOTAL_VERTS);
const VEL_DX = new Float32Array(TOTAL_VERTS);
const VEL_DY = new Float32Array(TOTAL_VERTS);
let meshStateInitialized = false;

function buildRestMesh() {
  const baseRowsY = [
    0.0,    // r=0: top studio frame edge (100% static)
    142.0,  // r=1: crown hair top
    240.0,  // r=2: forehead & hairline
    328.0,  // r=3: eyebrows
    356.0,  // r=4: upper eyelids
    371.0,  // r=5: lower eyelids
    440.0,  // r=6: nose base / sub-nasale / malar cheeks
    473.0,  // r=7: upper lip top border
    482.0,  // r=8: upper lip bottom border
    484.0,  // r=9: upper teeth bottom / lip parting seam
    485.0,  // r=10: lower lip top border
    504.0,  // r=11: lower lip bottom border
    563.0,  // r=12: chin tip & lower jaw border
    622.0,  // r=13: supple feminine neck transition zone
    700.0,  // r=14: collarbone & white blouse neckline (100% static)
    795.0,  // r=15: tailored cream blazer shoulders (100% static)
    885.0,  // r=16: mid-bust blazer lapels (100% static)
    995.0,  // r=17: lower blazer torso (100% static)
    1200.0, // r=18: bottom studio frame edge (100% static)
  ];

  for (let r = 0; r < NUM_ROWS; r++) {
    for (let c = 0; c < NUM_COLS; c++) {
      const idx = r * NUM_COLS + c;
      REST_SX[idx] = GRID_X[c];
      let y = baseRowsY[r];

      if (c >= 5 && c <= 14) {
        const mIdx = c - 5;
        if (r === 7) y = UPPER_LIP_TOP_10[mIdx];
        else if (r === 8) y = UPPER_LIP_BOT_10[mIdx];
        else if (r === 9) y = UPPER_TEETH_BOT_10[mIdx];
        else if (r === 10) y = LOWER_LIP_TOP_10[mIdx];
        else if (r === 11) y = LOWER_LIP_BOT_10[mIdx];
        else if (r === 12) y = CHIN_JAW_10[mIdx];
      } else if (c === 4) {
        if (r === 7) y = 479.0;
        else if (r === 8) y = 483.5;
        else if (r === 9) y = 484.0;
        else if (r === 10) y = 484.5;
        else if (r === 11) y = 492.0;
        else if (r === 12) y = 548.0;
      } else if (c === 15) {
        if (r === 7) y = 479.0;
        else if (r === 8) y = 483.5;
        else if (r === 9) y = 484.0;
        else if (r === 10) y = 484.5;
        else if (r === 11) y = 492.0;
        else if (r === 12) y = 548.0;
      }

      // Eyelid anatomical curvature for left eye (c=3..6, center c=4 at x=392) and right eye (c=14..16, center c=15 at x=520)
      if (r === 4) {
        if (c === 3) y = 362.0;
        else if (c === 4) y = 355.0;
        else if (c === 5) y = 356.5;
        else if (c === 6) y = 363.0;
        else if (c === 14) y = 362.0;
        else if (c === 15) y = 355.0;
        else if (c === 16) y = 363.0;
      } else if (r === 5) {
        if (c === 3) y = 369.0;
        else if (c === 4) y = 371.5;
        else if (c === 5) y = 371.0;
        else if (c === 6) y = 369.5;
        else if (c === 14) y = 370.0;
        else if (c === 15) y = 371.5;
        else if (c === 16) y = 369.0;
      }

      REST_SY[idx] = y;
      CUR_DX[idx] = GRID_X[c];
      CUR_DY[idx] = y;
    }
  }
}
buildRestMesh();

const REST_OPEN = 0.04;

const NUM_TRIS = (NUM_ROWS - 1) * (NUM_COLS - 1) * 2; // 648 triangles
const GL_VERTS = new Float32Array(NUM_TRIS * 3 * 4);

function deformMeshForFrame(frame: AvatarComputedFrame) {
  // Expressive feminine head inclination ('tilt' up to ±5.2 deg) around cervical pivot (454, 538)
  const clampedTiltDeg = Math.max(-5.2, Math.min(5.2, frame.tilt || 0));
  const tiltRad = (clampedTiltDeg * Math.PI) / 180.0;
  const cosT = Math.cos(tiltRad);
  const sinT = Math.sin(tiltRad);

  const open = frame.open;
  const roundness = frame.roundness;
  const spread = frame.spread;
  const jawDy = frame.jawDy;
  const browFurrow = frame.browFurrow ?? 0;
  const eyeWide = frame.eyeWide ?? 0.14;
  const cheekLift = frame.cheekLift ?? 0.45;
  const rawSmile = frame.smile ?? 0.72;
  const extraSmile = Math.max(0, rawSmile - 0.14);
  const intonation = frame.intonation ?? 0.24;
  const leftShoulderLift = frame.leftShoulderLift ?? frame.shoulderLift ?? 0;
  const rightShoulderLift = frame.rightShoulderLift ?? frame.shoulderLift ?? 0;
  const collarLift = frame.collarLift ?? (leftShoulderLift + rightShoulderLift) * 0.38;
  const torsoSwayX = frame.torsoSwayX ?? 0;

  const closeRatio = open <= REST_OPEN ? 1 - open / REST_OPEN : 0;
  const openRatio = open > REST_OPEN ? (open - REST_OPEN) / (1 - REST_OPEN) : 0;

  for (let r = 0; r < NUM_ROWS; r++) {
    for (let c = 0; c < NUM_COLS; c++) {
      const idx = r * NUM_COLS + c;
      let lx = REST_SX[idx];
      let ly = REST_SY[idx];

      // =======================================================================
      // 0. STATIC STUDIO BACKGROUND & CONTINUOUS SOFT BOUNDARY LOCK:
      // Outer frame edges (r === 0, r === NUM_ROWS - 1, c === 0, c === NUM_COLS - 1) anchor smoothly
      // without creating any hard rectangular seam or shear line on Aïsha's torso/body!
      // =======================================================================
      const isStaticAnchor =
        r === 0 ||
        r === NUM_ROWS - 1 ||
        c === 0 ||
        c === NUM_COLS - 1;
      if (isStaticAnchor) {
        TARGET_DX[idx] = lx;
        TARGET_DY[idx] = ly;
        CUR_DX[idx] = lx;
        CUR_DY[idx] = ly;
        continue;
      }

      // =======================================================================
      // 1. NATURAL FACIAL EXPRESSIONS, EYEBROWS, EYES, DUCHENNE SMILE & WAV2LIP
      // =======================================================================

      // A. Eyebrows & Forehead (r=2..3, c=3..15)
      const extraBrowLift = Math.max(0, frame.eyebrowLift - 0.18);
      if (r === 3 && c >= 3 && c <= 15) {
        const isLeftBrow = c >= 3 && c <= 8;
        const isRightBrow = c >= 12 && c <= 15;
        const browWeight = isLeftBrow
          ? c === 3
            ? 0.60
            : c >= 4 && c <= 7
            ? 1.05
            : 0.78
          : isRightBrow
          ? c === 15
            ? 0.70
            : 1.00
          : 0.38;
        const intonArch = isLeftBrow ? intonation * 1.25 : isRightBrow ? intonation * 1.18 : intonation * 0.42;
        const smileBrowArch = extraSmile * 1.05 * browWeight;
        const isInnerLeftBrow = c === 7 || c === 8;
        const isInnerRightBrow = c === 11 || c === 12;
        const furrowDown =
          isInnerLeftBrow || isInnerRightBrow || (c >= 9 && c <= 10)
            ? browFurrow * 2.5
            : -browFurrow * 1.1;

        ly -= (extraBrowLift * 5.4 + intonArch + smileBrowArch) * browWeight - furrowDown;
        if (isInnerLeftBrow) {
          lx += browFurrow * 2.4;
        } else if (isInnerRightBrow) {
          lx -= browFurrow * 2.4;
        }
      } else if (r === 2 && c >= 3 && c <= 15) {
        ly -= extraBrowLift * 1.8 + intonation * 0.45 - browFurrow * 0.5;
      }

      // B. Upper & Lower Eyelids (r=4..5, c=3..15): Anchored to natural eye pixels
      if (r === 4) {
        const extraWide = Math.max(0, eyeWide - 0.14);
        if (c >= 3 && c <= 6) {
          const w = c === 4 ? 1.0 : c === 5 ? 0.86 : 0.42;
          const wideLift = (1 - frame.blinkLeft) * extraWide * 1.35 * w;
          ly += frame.blinkLeft * 15.0 * w - wideLift + frame.gazeY * 0.30;
          lx += frame.gazeX * 0.32;
        } else if (c >= 14 && c <= 15) {
          const w = c === 15 ? 1.0 : 0.78;
          const wideLift = (1 - frame.blinkRight) * extraWide * 1.35 * w;
          ly += frame.blinkRight * 14.5 * w - wideLift + frame.gazeY * 0.30;
          lx += frame.gazeX * 0.32;
        }
      } else if (r === 5) {
        const duchenneSquint = extraSmile * 2.1;
        if (c >= 3 && c <= 6) {
          const w = c === 4 || c === 5 ? 1.0 : 0.52;
          ly += -duchenneSquint * w + frame.gazeY * 0.24;
          lx += frame.gazeX * 0.25;
        } else if (c >= 14 && c <= 15) {
          const w = c === 15 ? 1.0 : 0.60;
          ly += -duchenneSquint * w + frame.gazeY * 0.24;
          lx += frame.gazeX * 0.25;
        }
      }

      // B2. Mid-Cheeks & Zygomaticus Major ("Pommettes du sourire", r=6, c=3..15)
      if (r === 6 && c >= 3 && c <= 15) {
        const extraCheek = Math.max(0, cheekLift - 0.18);
        if (c >= 3 && c <= 7) {
          const leftCheekW = c === 4 || c === 5 ? 1.05 : c === 3 || c === 6 ? 0.82 : 0.46;
          ly += (-extraSmile * 4.4 - extraCheek * 2.3 + Math.max(0, jawDy) * 0.14) * leftCheekW;
          lx += (-extraSmile * 2.4 - roundness * 1.4) * leftCheekW;
        } else if (c >= 12 && c <= 15) {
          const rightCheekW = c === 14 || c === 15 ? 1.05 : 0.68;
          ly += (-extraSmile * 4.2 - extraCheek * 2.2 + Math.max(0, jawDy) * 0.14) * rightCheekW;
          lx += (extraSmile * 2.4 + roundness * 1.4) * rightCheekW;
        }
      }

      // B3. Outer Cheeks, Nasolabial Folds & Mandible Angles (r=7..12, c=3..4 and c=15)
      if (r >= 7 && r <= 12 && (c === 3 || c === 4 || c === 15)) {
        const isLeftZone = c <= 4;
        const colW = c === 4 ? 0.85 : c === 3 ? 0.44 : 0.82;
        const rowJawW =
          r === 7
            ? 0.16
            : r === 8
            ? 0.24
            : r === 9
            ? 0.35
            : r === 10
            ? 0.52
            : r === 11
            ? 0.68
            : 0.78;
        const rowSmileFactor = r <= 9 ? 1.08 : r === 10 ? 0.85 : r === 11 ? 0.52 : 0.24;
        const smileLift = extraSmile * 5.2 * rowSmileFactor * colW;
        const leftRelease = isLeftZone && openRatio > 0 ? openRatio * 0.75 * colW : 0;
        ly += Math.max(0, jawDy) * rowJawW * colW + leftRelease - smileLift;

        const smileOutward = extraSmile * 3.1 * (r <= 10 ? 1.0 : 0.45);
        const horizShift = isLeftZone
          ? (roundness * 4.2 - spread * 1.6 - smileOutward) * colW
          : (-roundness * 4.0 + spread * 1.5 + smileOutward) * colW;
        lx += horizShift;
      }

      // =======================================================================
      // C. WAV2LIP MOUTH ARTICULATION + RADIANT DUCHENNE SMILE ("INSÉRER LE SOURIRE"):
      // =======================================================================
      if (r >= 7 && r <= 12 && c >= 5 && c <= 14) {
        const speechActive = frame.mouthOpacity === '1';
        const mIdx = c - 5;
        const baseRestX = lx;
        const baseRestY = ly;

        const baseDome = STATION_DOME_W[mIdx];
        const normDist = (mIdx - 4.5) / 4.5;
        const absNorm = Math.abs(normDist);
        const centerBell = Math.max(0, 1 - absNorm * absNorm);
        const cornerCurve = Math.pow(absNorm, 1.45);

        const effectiveExtraSmile = speechActive ? extraSmile * (1 - roundness * 0.72) : extraSmile;
        // Upward crescent smile lift at mouth corners (-8.6px at full smile) + subtle center upper-lip smile arch
        const smileCornerLiftDy =
          -effectiveExtraSmile * 8.6 * cornerCurve -
          (r <= 8 ? effectiveExtraSmile * 1.4 * centerBell : 0);
        const cornerPinchWeight = 0.42 + 0.58 * Math.sin(absNorm * (Math.PI / 2));
        const smileStretchDx = normDist * effectiveExtraSmile * 5.0 * cornerPinchWeight;

        if (!speechActive && Math.abs(open - REST_OPEN) < 0.008) {
          lx = baseRestX + (r >= 7 && r <= 11 ? smileStretchDx : smileStretchDx * 0.30);
          ly =
            baseRestY +
            (r >= 7 && r <= 11 ? smileCornerLiftDy : smileCornerLiftDy * 0.25);
        } else {
          const roundNarrowing = Math.max(
            0.16,
            1 - roundness * Math.min(0.84, absNorm * 1.08)
          );
          const arcW = baseDome * roundNarrowing;

          const roundDx =
            r >= 7 && r <= 11
              ? -normDist * roundness * 12.2 * cornerPinchWeight +
                normDist * spread * 4.2 * cornerPinchWeight +
                smileStretchDx -
                normDist * openRatio * (1 - spread) * (1 - roundness) * 2.6 * cornerPinchWeight
              : -normDist * roundness * 3.2 * cornerPinchWeight + smileStretchDx * 0.22;

          const origUpperLipH = UPPER_LIP_BOT_10[mIdx] - UPPER_LIP_TOP_10[mIdx];
          const origFullTeethH = Math.max(0.4, UPPER_TEETH_BOT_10[mIdx] - UPPER_LIP_BOT_10[mIdx]);
          const origLowerLipH = LOWER_LIP_BOT_10[mIdx] - LOWER_LIP_TOP_10[mIdx];

          const speakingUpperTeethH =
            origFullTeethH * Math.max(0.14, 0.42 - roundness * 0.28 + spread * 0.14 + effectiveExtraSmile * 0.10);

          const cornerSmileDy =
            smileCornerLiftDy +
            (absNorm > 0.42 ? (-spread * 2.2 + roundness * 2.0) * (absNorm - 0.42) : 0);

          let targetY = baseRestY;

          if (open <= REST_OPEN) {
            const seamY =
              UPPER_LIP_BOT_10[mIdx] * 0.48 +
              LOWER_LIP_TOP_10[mIdx] * 0.52 +
              smileCornerLiftDy;
            // Preserve a warm smiling lip crescent during inter-clause pauses when smiling
            const isBilabial = frame.activeVisemeNumber === 1 && speechActive && (frame.roundness || 0) > 0.08;
            const smileRelax = isBilabial ? 1.0 : Math.max(0.35, 1 - effectiveExtraSmile * 0.55);
            const sealFactor = Math.min(1, Math.max(0, closeRatio)) * smileRelax;

            const curR8 = UPPER_LIP_BOT_10[mIdx] * (1 - sealFactor * 0.5) + (seamY - 0.1) * (sealFactor * 0.5) + smileCornerLiftDy * (1 - sealFactor * 0.5);
            const curR9 = seamY;
            const curR10 = LOWER_LIP_TOP_10[mIdx] * (1 - sealFactor * 0.5) + (seamY + 0.1) * (sealFactor * 0.5) + smileCornerLiftDy * (1 - sealFactor * 0.5);

            if (r === 7) targetY = curR8 - origUpperLipH;
            else if (r === 8) targetY = curR8;
            else if (r === 9) targetY = curR9;
            else if (r === 10) targetY = curR10;
            else if (r === 11) targetY = curR10 + origLowerLipH;
            else if (r === 12) targetY = CHIN_JAW_10[mIdx];
          } else {
            const puckerCushion = roundness * (0.45 + 0.55 * centerBell) * 3.4;
            const effectiveJawDrop =
              Math.max(
                1.4,
                (jawDy * 1.15 + openRatio * 23.5 * (1 - roundness * 0.42)) * 0.64
              );
            const upperLipShift =
              (-openRatio * (1 - roundness * 0.65) * 3.4 * centerBell +
                roundness * (2.2 - centerBell * 1.5) -
                intonation * 0.65) *
                arcW +
              cornerSmileDy;
            const curR8 = UPPER_LIP_BOT_10[mIdx] + upperLipShift;
            const curR9 = curR8 + speakingUpperTeethH;
            const curR10 =
              LOWER_LIP_TOP_10[mIdx] +
              effectiveJawDrop * arcW +
              cornerSmileDy -
              roundness * (1 - centerBell) * 3.8;

            if (r === 7) {
              targetY = curR8 - origUpperLipH * (1 + roundness * 0.32) - puckerCushion * 0.55;
            } else if (r === 8) {
              targetY = curR8;
            } else if (r === 9) {
              targetY = curR9;
            } else if (r === 10) {
              targetY = Math.max(curR9 + 0.35, curR10);
            } else if (r === 11) {
              targetY =
                Math.max(curR9 + 0.35, curR10) +
                origLowerLipH * (1 + roundness * 0.36 + openRatio * 0.14) +
                puckerCushion * 0.70;
            } else if (r === 12) {
              targetY =
                CHIN_JAW_10[mIdx] + effectiveJawDrop * Math.max(0.54, arcW) * 0.74;
            }
          }

          lx = baseRestX + roundDx;
          ly = targetY;
        }
      }

      // =======================================================================
      // 2. FULL CONVERSATIONAL & LISTENING 3D HEAD MOVEMENT + UPPER-BODY SHOULDER SHRUGS
      // =======================================================================
      if (r >= 1 && r <= 12) {
        // Smoothly taper outer background corner vertices at r=12 (c=2, 16) to prevent lower-bun shear
        const rowTaper =
          r === 12 && (c === 2 || c === 16)
            ? 0.45
            : r === 1 && (c === 2 || c === 16)
            ? 0.55
            : 1.0;
        const yawW = YAW_PERSPECTIVE_W[c] * rowTaper;
        const rx = lx - HEAD_PIVOT_X;
        const ry = ly - HEAD_PIVOT_Y;
        // Subtle coupling of cervical base with upper-body collar breath & torso sway
        const bodyCoupledX = torsoSwayX * 0.25 * rowTaper;
        const bodyCoupledY = collarLift * 0.28 * rowTaper;
        const rotX = HEAD_PIVOT_X + frame.turn * yawW + bodyCoupledX + (rx * cosT - ry * sinT);
        const rotY = HEAD_PIVOT_Y + frame.nod * yawW + bodyCoupledY + (rx * sinT + ry * cosT);

        TARGET_DX[idx] = lx * (1 - rowTaper) + rotX * rowTaper;
        TARGET_DY[idx] = ly * (1 - rowTaper) + rotY * rowTaper;
      } else if (r === 13) {
        // Supple feminine neck, white blouse collar & inner shoulders (y=622):
        // Combines smooth cervical neck follow with TTS-triggered shoulder shrugs & collar lift!
        const colNeckW =
          c <= 1 || c >= 17
            ? 0.0
            : c === 2 || c === 16
            ? 0.16
            : c === 3 || c === 15
            ? 0.30
            : 0.46;
        const neckWeight = colNeckW * YAW_PERSPECTIVE_W[c];
        const rx = lx - HEAD_PIVOT_X;
        const ry = ly - HEAD_PIVOT_Y;
        const headX = HEAD_PIVOT_X + frame.turn * YAW_PERSPECTIVE_W[c] + (rx * cosT - ry * sinT);
        const headY = HEAD_PIVOT_Y + frame.nod * 0.55 + (rx * sinT + ry * cosT);

        const isLeftShoulder = c <= 7;
        const isRightShoulder = c >= 11;
        const shoulderColW =
          c === 1 || c === 17
            ? 0.55
            : c === 2 || c === 16
            ? 0.92
            : c === 3 || c === 15
            ? 1.00
            : c === 4 || c === 14
            ? 0.85
            : 0.65;
        const shrugDy = isLeftShoulder
          ? leftShoulderLift * shoulderColW
          : isRightShoulder
          ? rightShoulderLift * shoulderColW
          : collarLift * 0.85;
        const shrugInwardDx = isLeftShoulder
          ? -Math.min(0, leftShoulderLift) * 0.22 * shoulderColW
          : isRightShoulder
          ? Math.min(0, rightShoulderLift) * 0.22 * shoulderColW
          : 0;

        TARGET_DX[idx] =
          lx * (1 - neckWeight) + headX * neckWeight + torsoSwayX * 0.55 + shrugInwardDx;
        TARGET_DY[idx] = ly * (1 - neckWeight) + headY * neckWeight + shrugDy;
      } else if (r >= 14 && r <= 17) {
        // Tailored cream blazer shoulders, lapels & upper bust (r=14..17):
        // Smooth continuous cosine falloff down to the bottom frame without any hard rectangular seam or shear!
        const rowWeight = Math.pow(Math.cos(((r - 14) / 4) * (Math.PI / 2)), 1.6);
        const colFactor = Math.sin((c / (NUM_COLS - 1)) * Math.PI);
        const isLeftShoulder = c <= 7;
        const isRightShoulder = c >= 11;
        const shoulderProfileW =
          (c === 1 || c === 17
            ? 0.50
            : c === 2 || c === 16
            ? 0.85
            : c === 3 || c === 15
            ? 1.00
            : c === 4 || c === 14
            ? 0.86
            : 0.68) * colFactor;

        const verticalShrug = isLeftShoulder
          ? leftShoulderLift * shoulderProfileW
          : isRightShoulder
          ? rightShoulderLift * shoulderProfileW
          : collarLift * 0.78;

        const clavicleDrawDx = isLeftShoulder
          ? -Math.min(0, leftShoulderLift) * 0.22 * shoulderProfileW
          : isRightShoulder
          ? Math.min(0, rightShoulderLift) * 0.22 * shoulderProfileW
          : 0;

        TARGET_DX[idx] = lx + (torsoSwayX * 0.50 + clavicleDrawDx) * rowWeight;
        TARGET_DY[idx] = ly + verticalShrug * rowWeight;
      }

      // =======================================================================
      // 3. PER-VERTEX TEMPORAL STATE-SPACE SMOOTHING (Kalman-style alpha-beta filter):
      // - Mouth vertices (r=7..11, c=5..14) track voice with ultra-fast zero-lag gain (alpha=0.86)
      // - Head & hair vertices track with silky velocity-damped smoothing (alpha=0.52, beta=0.14)
      //   to eliminate 100% of micro-saccades and frame-time jitter!
      // =======================================================================
      if (!meshStateInitialized) {
        CUR_DX[idx] = TARGET_DX[idx];
        CUR_DY[idx] = TARGET_DY[idx];
        VEL_DX[idx] = 0;
        VEL_DY[idx] = 0;
      } else {
        const isMouthVertex = r >= 7 && r <= 12 && c >= 5 && c <= 14;
        const alpha = isMouthVertex ? 0.86 : 0.54;
        const beta = isMouthVertex ? 0.08 : 0.14;
        const damping = isMouthVertex ? 0.65 : 0.80;

        const predX = CUR_DX[idx] + VEL_DX[idx] * damping;
        const predY = CUR_DY[idx] + VEL_DY[idx] * damping;
        const errX = TARGET_DX[idx] - predX;
        const errY = TARGET_DY[idx] - predY;

        CUR_DX[idx] = predX + alpha * errX;
        CUR_DY[idx] = predY + alpha * errY;
        VEL_DX[idx] = VEL_DX[idx] * damping + beta * errX;
        VEL_DY[idx] = VEL_DY[idx] * damping + beta * errY;
      }

      // Guarantee strict vertical monotonicity within each column so no triangle ever folds
      if (r > 0) {
        const prevIdx = (r - 1) * NUM_COLS + c;
        if (CUR_DY[idx] < CUR_DY[prevIdx] + 0.08) {
          CUR_DY[idx] = CUR_DY[prevIdx] + 0.08;
        }
      }
    }
  }
  meshStateInitialized = true;
}

// Transform a point (x, y) in central head space by the active 3D head pose
function transformHeadPoint(x: number, y: number, frame: AvatarComputedFrame): [number, number] {
  const clampedTiltDeg = Math.max(-5.2, Math.min(5.2, frame.tilt || 0));
  const tiltRad = (clampedTiltDeg * Math.PI) / 180.0;
  const cosT = Math.cos(tiltRad);
  const sinT = Math.sin(tiltRad);
  const rx = x - HEAD_PIVOT_X;
  const ry = y - HEAD_PIVOT_Y;
  return [
    HEAD_PIVOT_X + frame.turn + (rx * cosT - ry * sinT),
    HEAD_PIVOT_Y + frame.nod + (rx * sinT + ry * cosT),
  ];
}

export interface Wav2LipViewport {
  x: number;
  y: number;
  w: number;
  h: number;
  tutorPersona?: string;
}

class SharedWav2LipWebGLCore {
  private glCanvas: HTMLCanvasElement | null = null;
  private gl: WebGLRenderingContext | null = null;
  private program: WebGLProgram | null = null;
  private vbo: WebGLBuffer | null = null;
  private texture: WebGLTexture | null = null;
  private img: HTMLImageElement | null = null;
  private bgImg: HTMLImageElement | null = null;
  private isReady = false;
  private posLoc = -1;
  private uvLoc = -1;

  constructor() {
    if (typeof document !== 'undefined') {
      this.init();
    }
  }

  private init() {
    try {
      const canvas = document.createElement('canvas');
      canvas.width = IMG_W;
      canvas.height = IMG_H;
      const gl = (canvas.getContext('webgl', {
        alpha: true,
        antialias: true,
        premultipliedAlpha: false,
        preserveDrawingBuffer: true,
      }) ||
        canvas.getContext('experimental-webgl')) as WebGLRenderingContext | null;

      if (gl) {
        this.glCanvas = canvas;
        this.gl = gl;
        this.setupShaders(gl);
      }

      // Static Studio Background with flower pots, shelves and warm ambient lighting (100% static)
      const bgImg = new Image();
      bgImg.crossOrigin = 'anonymous';
      bgImg.src = imgStudioBg;
      this.bgImg = bgImg;

      // Aïsha's high-definition foreground with transparent studio cutout
      const img = new Image();
      img.crossOrigin = 'anonymous';
      img.onload = () => {
        this.img = img;
        if (this.gl) {
          this.prepareZeroGhostSingleLayerTexture(this.gl, img);
        }
        this.isReady = true;
      };
      img.src = imgTutrice;
    } catch {
      // Fallback cleanly if WebGL is unavailable
    }
  }

  private setupShaders(gl: WebGLRenderingContext) {
    const vsSource = `
      attribute vec2 a_pos;
      attribute vec2 a_uv;
      varying vec2 v_uv;
      void main() {
        vec2 clip = vec2(
          (a_pos.x / ${IMG_W}.0) * 2.0 - 1.0,
          1.0 - (a_pos.y / ${IMG_H}.0) * 2.0
        );
        gl_Position = vec4(clip, 0.0, 1.0);
        v_uv = a_uv;
      }
    `;
    const fsSource = `
      precision mediump float;
      varying vec2 v_uv;
      uniform sampler2D u_tex;
      void main() {
        gl_FragColor = texture2D(u_tex, v_uv);
      }
    `;

    const compile = (type: number, src: string) => {
      const sh = gl.createShader(type);
      if (!sh) return null;
      gl.shaderSource(sh, src);
      gl.compileShader(sh);
      if (!gl.getShaderParameter(sh, gl.COMPILE_STATUS)) {
        gl.deleteShader(sh);
        return null;
      }
      return sh;
    };

    const vs = compile(gl.VERTEX_SHADER, vsSource);
    const fs = compile(gl.FRAGMENT_SHADER, fsSource);
    if (!vs || !fs) return;

    const prog = gl.createProgram();
    if (!prog) return;
    gl.attachShader(prog, vs);
    gl.attachShader(prog, fs);
    gl.linkProgram(prog);
    if (!gl.getProgramParameter(prog, gl.LINK_STATUS)) return;

    this.program = prog;
    this.posLoc = gl.getAttribLocation(prog, 'a_pos');
    this.uvLoc = gl.getAttribLocation(prog, 'a_uv');
    this.vbo = gl.createBuffer();
  }

  /**
   * Foreground texture upload (single continuous layer):
   * - The PNG already carries a clean ML matte: feathered alpha (~1.2px ramp) with person-color
   *   bleed into transparent texels, so LINEAR filtering at the silhouette never mixes in
   *   old-photo background colors (no halos, no "traces fantômes").
   * - Background alpha=0 texels warp with the mesh but stay invisible over the static studio bg.
   */
  private prepareZeroGhostSingleLayerTexture(gl: WebGLRenderingContext, img: HTMLImageElement) {
    const tex = gl.createTexture();
    if (!tex) return;
    gl.bindTexture(gl.TEXTURE_2D, tex);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR);
    gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, img);
    this.texture = tex;
  }

  public renderWarpedFullFrame(frame: AvatarComputedFrame): HTMLCanvasElement | HTMLImageElement | null {
    if (!this.isReady || !this.img) return null;

    deformMeshForFrame(frame);

    const gl = this.gl;
    if (!gl || !this.program || !this.vbo || !this.texture || !this.glCanvas) {
      return this.img;
    }

    let ptr = 0;
    const emit = (r: number, c: number) => {
      const idx = r * NUM_COLS + c;
      GL_VERTS[ptr++] = CUR_DX[idx];
      GL_VERTS[ptr++] = CUR_DY[idx];
      GL_VERTS[ptr++] = REST_SX[idx] / IMG_W;
      GL_VERTS[ptr++] = REST_SY[idx] / IMG_H;
    };

    for (let r = 0; r < NUM_ROWS - 1; r++) {
      for (let c = 0; c < NUM_COLS - 1; c++) {
        emit(r, c);
        emit(r, c + 1);
        emit(r + 1, c);
        emit(r, c + 1);
        emit(r + 1, c + 1);
        emit(r + 1, c);
      }
    }

    gl.viewport(0, 0, IMG_W, IMG_H);
    gl.clearColor(0.0, 0.0, 0.0, 0.0);
    gl.clear(gl.COLOR_BUFFER_BIT);
    gl.useProgram(this.program);
    gl.enable(gl.BLEND);
    gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);
    gl.bindTexture(gl.TEXTURE_2D, this.texture);
    gl.bindBuffer(gl.ARRAY_BUFFER, this.vbo);
    gl.bufferData(gl.ARRAY_BUFFER, GL_VERTS, gl.DYNAMIC_DRAW);

    gl.enableVertexAttribArray(this.posLoc);
    gl.vertexAttribPointer(this.posLoc, 2, gl.FLOAT, false, 16, 0);
    gl.enableVertexAttribArray(this.uvLoc);
    gl.vertexAttribPointer(this.uvLoc, 2, gl.FLOAT, false, 16, 8);

    gl.drawArrays(gl.TRIANGLES, 0, NUM_TRIS * 3);
    return this.glCanvas;
  }

  // HiDPI backing-store metadata per target canvas.
  // Captures the authored attribute size + first-seen CSS box so the backing
  // store can be scaled by devicePixelRatio WITHOUT changing framing: the
  // viewport crop math below only depends on the backing aspect ratio, which
  // stays equal to the authored attribute aspect while the CSS box scales.
  private targetMeta = new WeakMap<
    HTMLCanvasElement,
    { w0: number; h0: number; cw0: number; ch0: number; lastW: number; lastH: number }
  >();

  private syncTargetBackingStore(targetCanvas: HTMLCanvasElement) {
    const cssW = targetCanvas.clientWidth;
    const cssH = targetCanvas.clientHeight;
    // Hidden (display:none) canvases have no CSS box: keep the authored size.
    if (cssW === 0 || cssH === 0) return;

    let meta = this.targetMeta.get(targetCanvas);
    if (!meta || targetCanvas.width !== meta.lastW || targetCanvas.height !== meta.lastH) {
      // First sighting, or the attribute size was rewritten externally
      // (React variant switch re-assigns width/height props).
      meta = {
        w0: targetCanvas.width,
        h0: targetCanvas.height,
        cw0: cssW,
        ch0: cssH,
        lastW: targetCanvas.width,
        lastH: targetCanvas.height,
      };
      this.targetMeta.set(targetCanvas, meta);
    }

    const dpr = Math.min(
      typeof window !== 'undefined' ? window.devicePixelRatio || 1 : 1,
      2
    );
    const wantW = Math.round(cssW * dpr * (meta.w0 / meta.cw0));
    const wantH = Math.round(cssH * dpr * (meta.h0 / meta.ch0));
    if (wantW > 0 && wantH > 0 && (targetCanvas.width !== wantW || targetCanvas.height !== wantH)) {
      targetCanvas.width = wantW;
      targetCanvas.height = wantH;
      meta.lastW = wantW;
      meta.lastH = wantH;
    }
  }

  public renderToTargetCanvas(
    targetCanvas: HTMLCanvasElement,
    viewport: Wav2LipViewport,
    frame: AvatarComputedFrame,
    sourceSurface: HTMLCanvasElement | HTMLImageElement | null
  ) {
    if (!sourceSurface) return;
    const ctx = targetCanvas.getContext('2d');
    if (!ctx) return;

    this.syncTargetBackingStore(targetCanvas);

    const cw = targetCanvas.width;
    const ch = targetCanvas.height;
    if (cw === 0 || ch === 0) return;

    // High-quality resampling for every drawImage (static bg + warped frame):
    // the backing store is now up to 2x the CSS box, so scaling matters.
    ctx.imageSmoothingEnabled = true;
    ctx.imageSmoothingQuality = 'high';

    // 1. Draw the static background + animated foreground
    const scale = Math.max(cw / viewport.w, ch / viewport.h);
    const drawW = cw / scale;
    const drawH = ch / scale;
    const sx = Math.max(0, Math.min(IMG_W - drawW, viewport.x + (viewport.w - drawW) * 0.5));
    const sy = Math.max(0, Math.min(IMG_H - drawH, viewport.y + (viewport.h - drawH) * 0.5));

    ctx.save();
    ctx.clearRect(0, 0, cw, ch);

    ctx.scale(scale, scale);
    ctx.translate(-sx, -sy);

    // 1. 100% STATIC STUDIO BACKGROUND WITH FLOWER POTS & PEDAGOGICAL DECOR
    // Rendered directly in static target coordinate space - completely immune to mesh deformation!
    if (this.bgImg && this.bgImg.complete && this.bgImg.naturalWidth > 0) {
      ctx.drawImage(this.bgImg, 0, 0, IMG_W, IMG_H);
    } else {
      const bgGrad = ctx.createLinearGradient(0, 0, 0, IMG_H);
      bgGrad.addColorStop(0, '#1E293B');
      bgGrad.addColorStop(1, '#0F172A');
      ctx.fillStyle = bgGrad;
      ctx.fillRect(0, 0, IMG_W, IMG_H);
    }

    // 2. AÏSHA'S 60 FPS ANIMATED FOREGROUND (Warped head, smile, eyes & breathing shoulders)
    ctx.drawImage(sourceSurface, 0, 0);

    // =========================================================================
    // 2. WAV2LIP ORAL CAVITY, UPPER CENTRAL INCISORS, ROSE-PINK TONGUE,
    //    LOWER INCISOR RIM & ROUNDED PUCKER APERTURE (COPIED FROM REFERENCE MODEL)
    // =========================================================================
    const speechActive = frame.mouthOpacity === '1';
    const cavOpacity = parseFloat(frame.cavityOpacity || '0');
    if (speechActive && cavOpacity > 0.02 && frame.open > 0.045) {
      ctx.save();
      ctx.globalAlpha = Math.min(1, cavOpacity);

      const roundPinch = frame.roundness || 0;
      const isPuckerMode = frame.activeVisemeNumber === 5 || roundPinch >= 0.45;
      const isSmilingViseme3 = frame.activeVisemeNumber === 3 || (frame.spread || 0) >= 0.45;

      const topPts: [number, number][] = [];
      const botPts: [number, number][] = [];
      for (let m = 0; m < 10; m++) {
        const c = 5 + m;
        const iTop = 9 * NUM_COLS + c;
        const iBot = 10 * NUM_COLS + c;
        const tx = CUR_DX[iTop];
        const ty = CUR_DY[iTop];
        const bx = CUR_DX[iBot];
        const by = CUR_DY[iBot];

        const lateralFactor =
          m === 0 || m === 9
            ? 1.0
            : m === 1 || m === 8
            ? isPuckerMode
              ? 0.88
              : isSmilingViseme3
              ? 0.10
              : 0.16 + roundPinch * 0.48
            : m === 2 || m === 7
            ? isPuckerMode
              ? 0.52
              : roundPinch * 0.28
            : 0;
        const midY = (ty + by) * 0.5;
        const effTy = ty * (1 - lateralFactor) + midY * lateralFactor - (m >= 2 && m <= 7 ? 0.45 : 0);
        const effBy = by * (1 - lateralFactor) + midY * lateralFactor + (m >= 2 && m <= 7 ? 1.15 : 0);

        topPts.push([tx, effTy]);
        botPts.push([bx, Math.max(effTy + 0.15, effBy)]);
      }

      ctx.beginPath();
      ctx.moveTo(topPts[0][0], topPts[0][1]);
      for (let i = 0; i < 9; i++) {
        const p0 = topPts[Math.max(0, i - 1)];
        const p1 = topPts[i];
        const p2 = topPts[i + 1];
        const p3 = topPts[Math.min(9, i + 2)];
        ctx.bezierCurveTo(
          p1[0] + (p2[0] - p0[0]) / 6,
          p1[1] + (p2[1] - p0[1]) / 6,
          p2[0] - (p3[0] - p1[0]) / 6,
          p2[1] - (p3[1] - p1[1]) / 6,
          p2[0],
          p2[1]
        );
      }
      for (let i = 9; i > 0; i--) {
        const p0 = botPts[Math.min(9, i + 1)];
        const p1 = botPts[i];
        const p2 = botPts[i - 1];
        const p3 = botPts[Math.max(0, i - 2)];
        ctx.bezierCurveTo(
          p1[0] + (p2[0] - p0[0]) / 6,
          p1[1] + (p2[1] - p0[1]) / 6,
          p2[0] - (p3[0] - p1[0]) / 6,
          p2[1] - (p3[1] - p1[1]) / 6,
          p2[0],
          p2[1]
        );
      }
      ctx.closePath();

      const midTopX = (topPts[4][0] + topPts[5][0]) * 0.5;
      const midTopY = (topPts[4][1] + topPts[5][1]) * 0.5;
      const midBotX = (botPts[4][0] + botPts[5][0]) * 0.5;
      const midBotY = Math.max(midTopY + 2.0, (botPts[4][1] + botPts[5][1]) * 0.5);
      const cavH = midBotY - midTopY;

      const oralGrad = ctx.createLinearGradient(0, midTopY, 0, midBotY);
      oralGrad.addColorStop(0, '#140407');
      oralGrad.addColorStop(0.38, '#280A10');
      oralGrad.addColorStop(1, '#1A060A');
      ctx.fillStyle = oralGrad;
      ctx.fill();

      ctx.save();
      ctx.clip();

      if (!isPuckerMode && roundPinch < 0.42) {
        // 1. Soft, plump rose-pink tongue filling the lower 72% of the oral cavity
        const tongueTopY = midTopY + cavH * (0.27 - (frame.tongueLift || 0) * 0.10);
        const tongueCx = (midTopX + midBotX) * 0.5;
        const tongueCy = (tongueTopY + midBotY) * 0.52 + cavH * 0.08;
        const tongueRx = Math.max(10.0, (topPts[7][0] - topPts[2][0]) * 0.54);
        const tongueRy = Math.max(3.5, cavH * 0.48);

        const tGrad = ctx.createRadialGradient(
          tongueCx - 1.5,
          tongueCy - tongueRy * 0.35,
          1.5,
          tongueCx,
          tongueCy,
          Math.max(tongueRx, tongueRy)
        );
        tGrad.addColorStop(0, '#CF868C');
        tGrad.addColorStop(0.45, '#B86E75');
        tGrad.addColorStop(0.80, '#964E55');
        tGrad.addColorStop(1, '#5E262C');

        ctx.beginPath();
        ctx.ellipse(tongueCx, tongueCy, tongueRx, tongueRy, 0, 0, Math.PI * 2);
        ctx.fillStyle = tGrad;
        ctx.fill();

        ctx.beginPath();
        ctx.moveTo(tongueCx, tongueTopY + 1.2);
        ctx.quadraticCurveTo(tongueCx + 0.4, tongueCy, tongueCx, midBotY - 1.5);
        ctx.strokeStyle = 'rgba(82, 30, 36, 0.28)';
        ctx.lineWidth = 1.2;
        ctx.stroke();

        // 2. Central Upper Incisors (subtle ivory edge under upper lip center, stations 2..7)
        const teethH = Math.min(3.2, Math.max(1.2, cavH * 0.22)) * (1 - roundPinch * 0.65);
        if (teethH > 0.7) {
          const tLeftX = topPts[2][0] * 0.7 + topPts[3][0] * 0.3;
          const tRightX = topPts[7][0] * 0.7 + topPts[6][0] * 0.3;
          const teethGrad = ctx.createLinearGradient(tLeftX, midTopY, tRightX, midTopY);
          teethGrad.addColorStop(0, '#9E8E89');
          teethGrad.addColorStop(0.22, '#EBE3DF');
          teethGrad.addColorStop(0.50, '#F7F3F0');
          teethGrad.addColorStop(0.78, '#EBE3DF');
          teethGrad.addColorStop(1, '#9E8E89');

          ctx.fillStyle = teethGrad;
          ctx.beginPath();
          ctx.moveTo(tLeftX, topPts[2][1] - 0.8);
          ctx.lineTo(tRightX, topPts[7][1] - 0.8);
          ctx.quadraticCurveTo(
            midTopX,
            midTopY + teethH,
            tLeftX,
            topPts[2][1] + teethH * 0.35
          );
          ctx.closePath();
          ctx.fill();
        }

        // 3. Subtle Lower Incisor / Wet Inner Mucosa Rim along the bottom curve (stations 2..7)
        if (cavH > 6.5) {
          const lLeftX = botPts[2][0] * 0.5 + botPts[3][0] * 0.5;
          const lRightX = botPts[7][0] * 0.5 + botPts[6][0] * 0.5;
          const lowTeethGrad = ctx.createLinearGradient(lLeftX, midBotY, lRightX, midBotY);
          lowTeethGrad.addColorStop(0, 'rgba(175, 152, 148, 0.45)');
          lowTeethGrad.addColorStop(0.5, 'rgba(232, 220, 216, 0.78)');
          lowTeethGrad.addColorStop(1, 'rgba(175, 152, 148, 0.45)');

          ctx.beginPath();
          ctx.moveTo(lLeftX, botPts[3][1] + 0.4);
          ctx.quadraticCurveTo(midBotX, midBotY - 1.6, lRightX, botPts[6][1] + 0.4);
          ctx.quadraticCurveTo(midBotX, midBotY + 0.8, lLeftX, botPts[3][1] + 0.4);
          ctx.closePath();
          ctx.fillStyle = lowTeethGrad;
          ctx.fill();
        }
      }

      ctx.strokeStyle = 'rgba(42, 14, 18, 0.68)';
      ctx.lineWidth = 2.0;
      ctx.stroke();

      ctx.restore();

      if (roundPinch >= 0.32) {
        ctx.save();
        ctx.globalAlpha = Math.min(0.42, (roundPinch - 0.25) * 0.75);
        ctx.strokeStyle = '#38181D';
        ctx.lineWidth = 1.1;
        ctx.lineCap = 'round';
        const offsets = [-9, -4, 4, 9];
        for (const dx of offsets) {
          ctx.beginPath();
          ctx.moveTo(midTopX + dx * 0.65, midTopY - 1.2);
          ctx.lineTo(midTopX + dx * 1.05, midTopY - 6.5);
          ctx.stroke();
          ctx.beginPath();
          ctx.moveTo(midBotX + dx * 0.65, midBotY + 1.2);
          ctx.lineTo(midBotX + dx * 1.10, midBotY + 7.5);
          ctx.stroke();
        }
        ctx.restore();
      }

      ctx.restore();
    }

    // =========================================================================
    // 2B. RADIANT DUCHENNE SMILE COMMISSURE DIMPLES & UPWARD LIP-CORNER CRESCENT
    //     ("insérer le sourire" — renders warm anatomical smile creases & lip lift)
    // =========================================================================
    const activeSmile = frame.smile ?? 0.72;
    if (activeSmile > 0.32) {
      const smileAlpha = Math.min(0.75, (activeSmile - 0.32) * 1.15) * (1 - (frame.roundness || 0) * 0.65);
      if (smileAlpha > 0.04) {
        const leftCornerIdx = 9 * NUM_COLS + 5;
        const rightCornerIdx = 9 * NUM_COLS + 14;
        const lx = CUR_DX[leftCornerIdx];
        const ly = CUR_DY[leftCornerIdx];
        const rx = CUR_DX[rightCornerIdx];
        const ry = CUR_DY[rightCornerIdx];

        ctx.save();
        ctx.lineCap = 'round';

        // Left commissure upward smile crease & dimple shadow
        ctx.globalAlpha = smileAlpha * 0.58;
        ctx.strokeStyle = '#3B1816';
        ctx.lineWidth = 1.7;
        ctx.beginPath();
        ctx.moveTo(lx + 2.2, ly + 0.8);
        ctx.quadraticCurveTo(lx - 2.6, ly - 1.8, lx - 5.4, ly - 5.2);
        ctx.stroke();

        // Right commissure upward smile crease & dimple shadow
        ctx.beginPath();
        ctx.moveTo(rx - 2.2, ry + 0.8);
        ctx.quadraticCurveTo(rx + 2.6, ry - 1.8, rx + 5.4, ry - 5.2);
        ctx.stroke();

        // Soft warm zygomaticus cheek-dimple cushion highlight above each corner
        ctx.globalAlpha = smileAlpha * 0.34;
        ctx.strokeStyle = '#D99B82';
        ctx.lineWidth = 1.4;
        ctx.beginPath();
        ctx.arc(lx - 4.5, ly - 2.6, 5.8, Math.PI * 0.78, Math.PI * 1.32);
        ctx.stroke();

        ctx.beginPath();
        ctx.arc(rx + 4.5, ry - 2.6, 5.8, -Math.PI * 0.32, Math.PI * 0.22);
        ctx.stroke();

        ctx.restore();
      }
    }

    // 3. Photorealistic Eyelid Skin & Lash Crease on Blinks / Winks (calibrated to exact y=355..371 eyes)
    if (frame.blinkLeft > 0.05) {
      const [x0, y0] = transformHeadPoint(373, 365, frame);
      const [xTop, yTop] = transformHeadPoint(395, 354.5, frame);
      const [xc, yc] = transformHeadPoint(395, 356 + frame.blinkLeft * 19.5, frame);
      const [x1, y1] = transformHeadPoint(417, 366, frame);
      ctx.save();
      ctx.globalAlpha = Math.min(1, frame.blinkLeft * 1.15);
      ctx.beginPath();
      ctx.moveTo(x0, y0);
      ctx.quadraticCurveTo(xTop, yTop, x1, y1);
      ctx.quadraticCurveTo(xc, yc, x0, y0);
      ctx.closePath();
      const lidGrad = ctx.createLinearGradient(0, yTop, 0, yc);
      lidGrad.addColorStop(0, '#A26850');
      lidGrad.addColorStop(0.65, '#86503B');
      lidGrad.addColorStop(1, '#5D3222');
      ctx.fillStyle = lidGrad;
      ctx.fill();

      ctx.beginPath();
      ctx.moveTo(x0, y0);
      ctx.quadraticCurveTo(xc, yc, x1, y1);
      ctx.strokeStyle = '#180805';
      ctx.lineWidth = 1.6;
      ctx.lineCap = 'round';
      ctx.stroke();
      ctx.restore();
    }

    if (frame.blinkRight > 0.05) {
      const [x0, y0] = transformHeadPoint(496, 366, frame);
      const [xTop, yTop] = transformHeadPoint(518, 354.5, frame);
      const [xc, yc] = transformHeadPoint(518, 356 + frame.blinkRight * 19.5, frame);
      const [x1, y1] = transformHeadPoint(540, 365, frame);
      ctx.save();
      ctx.globalAlpha = Math.min(1, frame.blinkRight * 1.15);
      ctx.beginPath();
      ctx.moveTo(x0, y0);
      ctx.quadraticCurveTo(xTop, yTop, x1, y1);
      ctx.quadraticCurveTo(xc, yc, x0, y0);
      ctx.closePath();
      const lidGrad = ctx.createLinearGradient(0, yTop, 0, yc);
      lidGrad.addColorStop(0, '#85513D');
      lidGrad.addColorStop(0.65, '#693B2A');
      lidGrad.addColorStop(1, '#482518');
      ctx.fillStyle = lidGrad;
      ctx.fill();

      ctx.beginPath();
      ctx.moveTo(x0, y0);
      ctx.quadraticCurveTo(xc, yc, x1, y1);
      ctx.strokeStyle = '#160704';
      ctx.lineWidth = 1.6;
      ctx.lineCap = 'round';
      ctx.stroke();
      ctx.restore();
    }

    ctx.restore();
  }
}

export const wav2lipWebGLCore = new SharedWav2LipWebGLCore();
